spring.application.name=account-service

server.port=8080

spring.mongodb.uri=mongodb+srv://kolambagekusal_db_user:08elgz9nL37PiET4@cluster0.dzqv2oc.mongodb.net/ridelink_account_db?appName=Cluster0
spring.mongodb.database=ridelink_account_db

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration-seconds=${JWT_EXPIRATION_SECONDS:36000}
